### ISSUE TITLE
Clarify lib's usage

### ISSUE THREAD

**Issue by wlsf82** [bahmutov/cypress-grep#27]
By reading the docs, it's not clear that it tries to run all spec files, even if some of them do not match the grepped word.

I have experimented with the Cypress examples, those created automatically when opening Cypress for the first time.
I ran `npx cypress run --env grep=blur`, and although there’s only one match for `blur` (on the `cypress/integration/examples/actions.spec.js` file, which successfully executed), all other specs were “run” as well (as pending).

Maybe that's the expected behavior, but better make it clear on the docs.

By the way, that's a great lib, thanks!

Cc @bahmutov.

**Comment by bahmutov** [comment]
Gotcha,

So the grep works at run-time, thus _all_ specs will still start as usual. Every test title will be evaluated against the grep string and if it matches the test will be allowed to run, otherwise, it will switch to `it.skip` - which is the pending test status https://glebbahmutov.com/blog/cypress-test-statuses/

I will add this note to the README

**Comment by erikmellum** [comment]
@bahmutov is it possible to hide skipped tests entirely? We would love for our CI process to show only the tests it runs, and none of the ones it skipped.

**Comment by bahmutov** [comment]
@erikmellum can you open a new issue about it? Since it will be an enhancement
